name: Builds and pushes image

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '**.sh'
  workflow_call:

jobs:
  docker:
    needs: inputs
    name: Deploy to DockerHub (latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: linux/arm,linux/arm64,linux/amd64
          push: true
          tags: |
            afonsoc12/backuo-utils:latest
            afonsoc12/backup-utils:${{ github.run_number }}
            ghcr.io/afonsoc12/backup-utils:latest
            ghcr.io/afonsoc12/backup-utils:${{ github.run_number }}

      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ needs.inputs.outputs.version }}
      #     release_name: ${{ needs.inputs.outputs.version }}
      #     draft: false
      #     prerelease: false
